version: '3'

services:
  db:
    container_name: xp-challenge-api_mysql
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - xp-challenge-api

networks:
  xp-challenge-api:
    name: xp-challenge-api